Algoritmo "CASO"

//ESTUDAR O COMANDO CASO/CASE
// Data atual  : 08/09/2022
Var
 x: caractere

Inicio

      escreval("digite uma letra: ")
      leia(x)
      escolha x
              caso "a"
                   escreval("voce digitou a letra A")
              caso "b"
                   escreval("voce digitou a letra B")
              outrocaso
                    escreval("voce digitou uma outra letra")
                    fimescolha


Fimalgoritmo