Algoritmo "PROCEDIMENTO"
//SUBROTINAS
// Data atual  : 08/09/2022
Var
   n: caractere
   x: caractere
   y: caractere
   procedimento texto(nome : caractere)
   inicio
         escreval("bom dia ", nome)
         fimprocedimento

Inicio
     escreval("digite seu nome: ")
     leia(n)
     texto(n)
     
     escreval("digite sua idade: ")
     leia(x)
     texto(x)
     
     escreval("parabens novinha")
     leia(y)
     texto(y)




Fimalgoritmo