Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2022
Var
// Seção de Declarações das variáveis 
   minhanota: real
   notas: vetor[0..9] de real

Inicio
      notas[0] <- 8.5
      minhanota <- notas[0]
      escreval(" A variavel contem: ", minhanota)
      escreval("o vetor no índice de posição 0, contém: ", notas[0])


Fimalgoritmo